# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{cssex}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["twoism"]
  s.date = %q{2009-12-30}
  s.default_executable = %q{cssex}
  s.description = %q{Create CSS Skeletons from HTML files}
  s.email = %q{signalstatic@gmail.com}
  s.executables = ["cssex"]
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "README"
  ]
  s.homepage = %q{http://github.com/twoism/cssex}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Create CSS Skeletons from HTML files}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

